[env]
CARGO = "cargo"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["isignkit_cli"]
CARGO_BUILD_RELEASE_ARG = { value = "--release", condition = { profiles = ["release"] } }
PROJECT_FAT_BINARY = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/isignkit"

# Bypass https://github.com/cross-rs/cross/pull/931
RUSTFLAGS = """ \
--remap-path-prefix=${HOME}= \
--remap-path-prefix=${CARGO_MAKE_CARGO_HOME}= \
--remap-path-prefix=${CARGO_MAKE_WORKING_DIRECTORY}= \
--remap-path-prefix=${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}= \
"""

[tasks.test]
category = "Test"
description = "Runs cargo test"
command = "cargo"
args = ["test", "--all-features"]

[tasks.build-target]
private = true
script_runner = "@duckscript"
script = '''
target_dir = join_path ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY} binaries
mkdir ${target_dir}

exec ${CARGO} build ${CARGO_BUILD_RELEASE_ARG} --target ${TARGET} -p isignkit_cli --no-default-features --features openssl-vendored

compiled_object =  join_path ${CARGO_MAKE_CRATE_TARGET_DIRECTORY} ${TARGET} ${CARGO_MAKE_PROFILE} isignkit
target_object = join_path ${target_dir} isignkit-${TARGET}

cp ${compiled_object} ${target_object}
'''

[tasks.build-macos-amd64]
category = "Build"
workspace = true
description = "Runs build for amd64 macOS. Requires macOS environment"
run_task = "build-target"
condition = { platforms = ["mac"], fail_message = "macOS binary can be compiled on macOS platform only." }

[tasks.build-macos-amd64.env]
TARGET = "x86_64-apple-darwin"

[tasks.build-macos-arm64]
category = "Build"
description = "Runs build for amd64 macOS. Requires macOS environment"
run_task = "build-target"
condition = { platforms = ["mac"], fail_message = "macOS binary can be compiled on macOS platform only." }

[tasks.build-macos-arm64.env]
TARGET = "aarch64-apple-darwin"

[tasks.build-macos]
category = "Build"
description = "Runs build for both macOS archs. Requires macOS environment"
dependencies = ["build-macos-amd64", "build-macos-arm64"]
script_runner = "@duckscript"
script = '''
target_dir = join_path ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY} binaries

binaries = array
array_push ${binaries} ${target_dir}/isignkit-aarch64-apple-darwin
array_push ${binaries} ${target_dir}/isignkit-x86_64-apple-darwin

binaries = array_join ${binaries} " "
exec bash -xc "lipo -create ${binaries} -o ${target_dir}/isignkit-macos; rm ${binaries}"
exec bash -xc "ldid -S -Cadhoc ${target_dir}/isignkit-macos 2>/dev/null || echo 'ldid is not installed, not signing...'"
'''
condition = { platforms = ["mac"], fail_message = "macOS binary can be compiled on macOS platform only." }
