[package]
name = "isignkit_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "isignkit"
path = "src/main.rs"

[features]
default = ["openssl"]
openssl = [
    "isignkit/openssl",
    "reqwest/native-tls",
]
openssl-vendored = [
    "isignkit/openssl-vendored",
    "reqwest/native-tls-vendored",
]

[dependencies]
anyhow = "1.0.102"
chrono = "0.4.44"
clap = { version = "4.6.1", features = ["derive"] }
isignkit = { path = "../isignkit", features = ["schema"] }
log = "0.4.29"
reqwest = { version = "0.13.3", default-features = false, features = ["blocking", "json", "query"] }
serde = "1.0.228"
serde_json = "1.0.149"
simple_logger = { version = "5.2.0", features = ["stderr"] }
url = "2.5.8"
