name: Perform release flow
on:
  push:
    tags: [ "v*" ]
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: cargo-bins/cargo-binstall@v1.15.5
      - name: Install additional dependencies
        run: cargo-binstall -y cargo-make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install target support
        run: |
          rustup target add aarch64-apple-darwin x86_64-apple-darwin
          rustup default stable
      - name: Compile in release configuration
        run: cargo build-mac
      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          files: target/sign-util
